// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG-DcP2pLzBdVn22Q4dy3q4SopqoQfx0k',
    appId: '1:1065791059225:android:77262cf89399c5b0248188',
    messagingSenderId: '1065791059225',
    projectId: 'trackit-42628',
    storageBucket: 'trackit-42628.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA82Jz-UvAwUq3gkDgXc8A8vSp5k10WdA',
    appId: '1:1065791059225:ios:c720e2d26ccd2f37248188',
    messagingSenderId: '1065791059225',
    projectId: 'trackit-42628',
    storageBucket: 'trackit-42628.firebasestorage.app',
    iosBundleId: 'com.example.trackIt',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsVONafD72a5AlQ8un0NeGwf1GZk-LrY4',
    appId: '1:1065791059225:web:790e44dc5901a192248188',
    messagingSenderId: '1065791059225',
    projectId: 'trackit-42628',
    authDomain: 'trackit-42628.firebaseapp.com',
    storageBucket: 'trackit-42628.firebasestorage.app',
    measurementId: 'G-VWMDNC5JS6',
  );

}